#!/bin/sh

SABAYON_LOADER="/usr/bin/xdg-open"
SABAYON_URL=${SABAYON_URL:-http://www.kogaion.org?install_welcome=1}

# load Kogaion URL
[[ -x "${SABAYON_LOADER}" ]] && ${SABAYON_LOADER} ${SABAYON_URL} &

# remove myself from autostart
rm ~/.config/autostart/kogaion-welcome-loader.desktop -f
